# Generated by Django 4.1.4 on 2023-07-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_msg_sms_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
