# Generated by Django 4.1.4 on 2023-07-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sms_send_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='originator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
